### ISSUE TITLE
Peformance of your reimplementation

### ISSUE THREAD

**Issue by CoderHHX** [solangii/TapNet-torch#5]
Hi @solangii!

Thanks for your insightful work! Could you please tell me the performance of your implementation of TapNet? I am also learning this wonderful paper.

Kind Regards,
HHX

**Comment by solangii** [comment]
Sorry for not having answered your issue sooner.

I'm so busy right now that it's hard to check right away. The reproduction results out lower than the performance in the paper. (As far as I can remember,) It showed about 2% lower performance. I couldn't proceed further because I was busy. I don't think this repo will be maintained in the future. I'm sorry I didn't tell you the good news. Thank you for your interest in my repo:)

**Comment by CoderHHX** [comment]
Well received and thanks for your reply!
